### PR TITLE
Jennifer/ten gateway

### PR DESCRIPTION
**Pull request by Jennievon**
### Why this change is needed

Please provide a description and a link to the underlying ticket

Revamp of Ten Gateway
https://github.com/ten-protocol/ten-internal/issues/2322

### What changes were made as part of this PR

Please provide a high level list of the changes made

Switched to NextJS

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

### CODE REVIEW

**Review by otherview — COMMENTED** [review]
Looks good ! I believe this should follow the pattern of obscuro scan with backend and frontend separated given that we're moving to a more robust solution.

**Review by 0xjba — APPROVED** [review]
LGTM

**Comment by Jennievon** [comment]
> Looks good ! I believe this should follow the pattern of obscuro scan with backend and frontend separated given that we're moving to a more robust solution.

Got it. Will add that update.

**Review by otherview — DISMISSED** [review]
Looks good ! A few changes I would sugest:

- Can main be merged in ? Seems like there are a lot of obscuro scan changes here
- Let's move the frontend to the base of the `walletextension`. From `walletextension/api/ten-gateway/frontend` to `walletextension/frontend`
- Create only 1 way of accessing the ethers/provider and avoid using window.ethereum. ( afaik 99% of the cases it's only required the active provider)
- Update the Readme with the folder meaning

**Comment by otherview** [comment]
@coderabbit pause

**Comment by otherview** [comment]
The FE code should build the distributable files to `walletextension/api/static` folder.

@zkokelj can you piggy back on this PR and make sure the files are correctly served from the go side ?

**Review by zkokelj — APPROVED** [review]
LGTM

**Pull request merged**
