### PR TITLE
refactor: naming conventions

### PR DESCRIPTION
**Pull request by Jennievon**
### Why this change is needed

Please provide a description and a link to the underlying ticket

### What changes were made as part of this PR

Please provide a high level list of the changes made

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

### CODE REVIEW

**Comment by otherview** [comment]
Worth merging in main first.

**Comment by Jennievon** [comment]
> It's probably worth merging in main first so that the code diff is smaller.

Done @otherview

**Review by otherview — APPROVED** [review]
Looks good ! I think we could tidy up the names as sugested below, but it's not a merge blocker imo.

Sugestion:
- Appending the folder naming: `export const fetchBatches = async (` -> `export const fetchBatchesAPI = async (` 
- `hooks` folder to be renamed to `services` (all the files are services)

**Comment by Jennievon** [comment]
> Looks good ! I think we could tidy up the names as sugested below, but it's not a merge blocker imo.
> 
> Sugestion:
> 
> * Appending the folder naming: `export const fetchBatches = async (` -> `export const fetchBatchesAPI = async (`
> * `hooks` folder to be renamed to `services` (all the files are services)

These would be addressed in a subsequent PR.

**Pull request merged**
