### PR TITLE
chore(contracts): a bit of proofreading

### PR DESCRIPTION
**Pull request by sqltrigger**
Came across few errors while studying the code, two of them are messages displayed to the user, the rest are comments.
Doesn't require changelog entry or testing.
Have a nice evening.

### CODE REVIEW

**Comment by otherview** [comment]
Nice one, thanks for that @sqltrigger 👏

**Comment by tudor-malene** [comment]
Thanks @sqltrigger . Unfortunately there is a conflict. 
Once you resolve it, I will merge your change.

**Comment by sqltrigger** [comment]
@tudor-malene Hopefully I did it right, have a nice week-end.

**Review by tudor-malene — APPROVED** [review]
Thank you for your contribution.
Looks good to me.

**Comment by tudor-malene** [comment]
> @tudor-malene Hopefully I did it right, have a nice week-end.

Thank you @sqltrigger . Merged

**Pull request merged**
